DBHouseholds_wealth_accounting
AggregateHouseholdsBankAccount(current_day)=DBHouseholds_bank_account_aggregation(current_day);
AggregateHouseholdsLiquidAssetsWealth(current_day)=DBHouseholds_liquid_assets_wealth_aggregation(current_day);

DBAMCs_wealth_accounting
AggregateAMCsBankAccount(current_day)=DBAMCs_bank_account_aggregation(current_day);
AggregateAMCsLiquidAssetsWealth(current_day)=DBAMCs_liquid_assets_wealth_aggregation(current_day);

Government.portfolio.bank_account(current_day) = ...
    Government.portfolio.bank_account(current_day-1) + ...
    Government.portfolio.transactions_accounting(current_day);
Government.liquid_assets_wealth(current_day) = ...
    agent_liquid_assets_wealth_computing(current_day,Government);

PensionFundManager.portfolio.bank_account(current_day) = ...
    PensionFundManager.portfolio.bank_account(current_day-1) + ...
    PensionFundManager.portfolio.transactions_accounting(current_day);
PensionFundManager.liquid_assets_wealth(current_day) = ...
    agent_liquid_assets_wealth_computing(current_day,PensionFundManager);


AggregateBankAccount(current_day) = AggregateHouseholdsBankAccount(current_day)+...
    AggregateAMCsBankAccount(current_day)+...
    Government.portfolio.bank_account(current_day)+...
    PensionFundManager.portfolio.bank_account(current_day);
    
AggregateLiquidAssetsWealth(current_day) = ...
    AggregateHouseholdsLiquidAssetsWealth(current_day)+...
    AggregateAMCsLiquidAssetsWealth(current_day)+...
    Government.liquid_assets_wealth(current_day)+...
    PensionFundManager.liquid_assets_wealth(current_day);

if Parameters.prompt_print==1
    fprintf('\r\r Aggregate liquid assets wealths and bank accounts')
    fprintf('\r\t Households: %f \t %f',...
        AggregateHouseholdsLiquidAssetsWealth(current_day),...
        AggregateHouseholdsBankAccount(current_day))
    fprintf('\r\t AMCs: %f \t %f',...
        AggregateAMCsLiquidAssetsWealth(current_day),...
        AggregateAMCsBankAccount(current_day))
    fprintf('\r\t Government: %f \t %f',...
        Government.liquid_assets_wealth(current_day),...
        Government.portfolio.bank_account(current_day))
    fprintf('\r\t Pension Fund Manager: %f \t %f',...
        PensionFundManager.liquid_assets_wealth(current_day),...
        PensionFundManager.portfolio.bank_account(current_day))    
    fprintf('\r\t Overall aggregates: %f \t %f',AggregateLiquidAssetsWealth(current_day),...
        AggregateBankAccount(current_day))
end